# Generated by Django 4.2.2 on 2023-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('fecha_llegada', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
